baseURL = "http://nginx.conf.in.th/"
languageCode = "en-us"
title = "Nginx.conf.in.th"
#theme = "geppaku"
theme = "hugo-theme-air"
disqusShortname = "nginx-conf-in-th"
googleAnalytics = "UA-67219536-2"


[author]
    # If you want to display author information set these
    # This is Optional values
    name = "Neverlock"

    # Please set account ids
    # This is Optional values
    twitter  = "neverlock"
    github   = "neverlock"

[params]
#for air theme START
description = "let's rock with nginx"
googleAnalyticsUserID = "UA-67219536-2"
#for air theme END
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        twitter  = true
        facebook = true
        # hatena   = true # hatena is Japanese social media
        google   = true

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        sidebar = "adsense/sidebar.html"
        #content = "adsense/content.html"
